version: '3'
services:
  app:
    build: .
    ports:
      - "5000:5000"

  web:
    build: .
    command: python app.py
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./static/:/app/static